### ISSUE TITLE
In GCM 2.3 we dropped the symlinks.

### ISSUE THREAD

**Issue by Alphanummeric** [awesome-lists/awesome-bash#100]
In GCM 2.3 we dropped the symlinks.
Let's update our docs on the issue to reflect this.

Rendered: https://github.com/git-ecosystem/git-credential-manager/blob/rename-docs-update/docs/rename.md

_Originally posted by @mjcheetham in https://github.com/git-ecosystem/git-credential-manager/pull/1363_

**Comment by kamiuyzc** [comment]
test
