### ISSUE TITLE
Request for new category `Logging` - `simbashlog`

### ISSUE THREAD

**Issue by fuchs-fabian** [awesome-lists/awesome-bash#133]
Unfortunately, I have not yet found a tool in the list that is written in Bash for logging in Bash scripts and Linux environments.

Since this is very important in my opinion and I have not found a 100% reliable tool myself, I have been writing a logger called `simbashlog` myself for weeks now. 

It would be very desirable if this could be integrated. I may not be the only one who has encountered this problem? 🙂

https://github.com/fuchs-fabian/simbashlog

What do you think?

**Comment by hyperupcall** [comment]
Thanks for the request! The project looks promising, but our [link requirements](https://github.com/awesome-lists/awesome-bash/blob/master/contributing.md#ground-rules) mention that the repository must have more than 50 stars or are at least 90 days old

**Comment by fuchs-fabian** [comment]
All right, thanks. I'll probably make another request around December 15th 🙂
