### ISSUE TITLE
does tools written in other languages but for bash count?

### ISSUE THREAD

**Issue by shinenelson** [awesome-lists/awesome-bash#51]
I've worked with [`bashly`](https://github.com/DannyBen/bashly) and it seemed like a good tool that could be on this list under the [Shell Script Development](https://github.com/awesome-lists/awesome-bash#shell-script-development) section. I think it works similar to [`bashing`](https://github.com/xsc/bashing) ( from the description of the project ), but I haven't used `bashing`, so I cannot confirm it.

However, the catch is that the tool itself is a ruby gem which means one needs to install a ruby environment and then install the gem to use it.

I know it is kind of counter intuitive, but I'd still like to at least give it a shot and ask ( no harm in asking right? ) whether it is acceptable on this list. I know the shell script development list is already long enough that it does not need another "non-native" member to alienate.

**Comment by aloisdg** [comment]
I don't know for other awesome lists, but as far as I concerned I would say that bashly does apply.

**Comment by aloisdg** [comment]
Bashly merged #66

**Comment by ajeetdsouza** [comment]
@aloisdg does https://github.com/awesome-lists/awesome-bash/pull/53 apply here too?

**Comment by aloisdg** [comment]
I will answer on #53
