### ISSUE TITLE
Is this actively maintained?

### ISSUE THREAD

**Issue by Knusper** [awesome-lists/awesome-bash#68]
Hi,
I see a couple of PRs that are quite old?
Before contributing I would like to ask if this list still has a maintainer?
Best,
Christian

**Comment by aloisdg** [comment]
Hi!

As the initiator of the list I can say that this list is not actively maintained. I would say "slighty" maintained. I don't use bash as much. If you want to involve yourself, I am willing to give right to active contributor.

**Comment by Knusper** [comment]
What does "active contributor" `imply` and what would be my duties?  Without any doubt I am willing to monitor regularly for PRs and check whether they are good.

**Comment by bradrf** [comment]
If this project needs more help, I'd also be happy to pitch in, as well.

One suggestion that might improve submissions, increase the quality of the list, and simplify maintenance is to take a similar approach to what the [awesome-cli contribution guidelines](https://github.com/agarrharr/awesome-cli-apps/blob/master/contributing.md#readme) outline, with clear goals of the list and required criteria for evaluation.

**Comment by aloisdg** [comment]
@bradrf great suggestion: contribution guidelines would fix #5

**Comment by aloisdg** [comment]
@Knusper mostly review PR and keep the list updated (link rotting) and organize. You can start by sharing you opinion on #53

**Comment by aloisdg** [comment]
btw @bradrf and @Knusper, thank you.

**Comment by aloisdg** [comment]
(If you are still around in a week and if you handle some issues/PR, I will give more rights).

**Comment by bradrf** [comment]
I'll open a PR with some of the same kinds of improvements around this project's contribution and PR template and see if we can help folks provide better info when opening a PR.

**Comment by aloisdg** [comment]
issue and PR templates are nice for that :)

**Comment by bradrf** [comment]
Took me too long to get to this, but I opened https://github.com/awesome-lists/awesome-bash/pull/71 with a suggestion around more contribution guidance along w/ a PR template. Lemme know what you think.

**Comment by aloisdg** [comment]
@bradrf Great work. Just let a comment on the "approval" number. I will be fine if we merge the PR as is.

**Comment by bradrf** [comment]
I don't currently have write privileges to merge the PR, so feel free if you think it's good to go:
![image](https://user-images.githubusercontent.com/295715/147132369-f514a7fa-7148-4b0b-b873-7a0d59b69b1a.png)

**Comment by aloisdg** [comment]
@bradrf merged. and you now have the rights to do it yourself next time.

**Comment by aloisdg** [comment]
I will close this issue for now.
