### ISSUE TITLE
Hey, looking for a project (you probably don't know either..)

### ISSUE THREAD

**Issue by SeanScherer** [awesome-lists/awesome-bash#86]
Hi, I stumbled over a project some time ago (but can't find it now that I'd like to use it :/ ... ).

Thought since this is a place bash enthusiasts are, maybe someone can help me (plus it'd make a great addition to the list!).

The projects idea was that whenever you setup an open source project (for compiling it yourself, etc.), first thing is you install the dependencies, often by running shell commands gleaned from the readme. That being a little tedious / ie manual work, plus the fact that readme's have a tendancy to go out of date, the solution was to have the "readme" be an interactive bash script, that sets up the dev environment for you. Ie, you'd have the established contributors use the "script" just the same as new people (this is what I understand / remember from memory).

The project, then, was a framework for setting up this "readme". (doesn't seem a super-complex task, but if it made things easy and well readable, seems worth it to me).

It did overall sound pretty neat to me, so I though maybe someone else might have seen this ?

Thanks and regards,
Sean.

**Comment by 1xyz** [comment]
Have you tried https://github.com/1xyz/pryrite ?
(disclaimer: I'm one of the authors)

**Comment by SeanScherer** [comment]
Not exactly what I had meant, but does look interesting :) !

(The project I meant had you set up a (bash)-script, which you could then prompt for the info you wanted - just in case that wasn't clear).

I'll definitely have a look into it for my personal stuff :) !

**Comment by hyperupcall** [comment]
I've seen [xc](https://github.com/joerdav/xc) and [mask](https://github.com/jacobdeichert/mask), which do something like this
