### ISSUE TITLE
My Contribution Scripts?

### ISSUE THREAD

**Issue by lexterror** [awesome-lists/awesome-bash#93]
Hi,

I recently created two bash shell scripts:

1. World Clock
2. Video Poker Game

if you think they are useful let me know!

https://github.com/lexterror/World-Clock-CLI-Linux-Android

https://github.com/lexterror/Video-Poker-Vice-CLI-Linux-Android

Thank you!

**Comment by lexterror** [comment]
Also, https://github.com/lexterror/Search-Everything-Script-Android-Termux

Its a search all script. I wrote it under a lex81 account because I could not remember my password for my current account.

**Comment by Knusper** [comment]
This all does not seem at a level that is expected for contributions to this list.

**Comment by lexterror** [comment]
Ok. The idea was to contribute material. I know Im no professional programmer. But things like the world clock and a search utility work without any issues and Im sure many beginners and users alike could benefit. Anyway thanks for responding.
